server:
  port : 8700  
spring:
  application:
    name: toDoConfigServer       
  profiles:
    active:
    - dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YugandharaP/ToDoCommonConfigurations.git

  